### ISSUE TITLE
protocol-handler

### ISSUE THREAD

**Issue by SoniEx2** [protocol-registries/well-known-uris#34] opened 2023-06-16 21:41 UTC
Please confirm that:

* [x] You have read and understood the [requirements for registration](https://tools.ietf.org/html/rfc8615#section-3.1).
* [x] You have checked [the registry](https://www.iana.org/assignments/well-known-uris/) and found no current value that meets your needs.
* [x] Your specification reference URL is stable; ideally, managed by a widely-recognised standards development organisation (e.g., published as an RFC). Otherwise, please give additional information.

If so, please enter the details of the well-known URI below:

* URI suffix: protocol-handler
* Change controller: Fedi-To https://fedi-to.net/
* Specification document(s): https://github.com/fedi-to/fedi-to.github.io/blob/main/protocol-handler.md

Any additional information (this will not be included in the registry)?

This is intended for webapps to freely interact with each other based on URLs. For example, Fediverse instances can use these to allow opening a post or profile on the reader's own instance based purely on a domain name. The target app then has to do some app-specific thing to try and open the URL in-app, or provide a helpful error message if it cannot.

It's not intended for *sharing* URLs with apps - that is, it's not intended for opening a message composition screen with the URL pre-filled. Web apps can use the [experimental `share_target` feature of web app manifests](https://developer.mozilla.org/en-US/docs/Web/Manifest/share_target) for that instead.

**Comment by mnot** [comment] 2023-06-19 01:41
Duplicate of #25

**Closed by mnot** 2023-06-19 01:41 UTC
Labels: new registration

**Comment by SoniEx2** [comment] 2023-06-19 01:52
uh okay, how do we re-submit these?
